Fix Garbled message in non-English Windows
atom-community/atom-script pull request #2470
Opened 2021-05-12 04:08 UTC by mhatano

Quick fix for the issue #1166, Java build in non-English editions of Window will result garbled message, stdout and stderr displayed.
Please note that this fix would have further issue: if user's final target deployment would have different encodings from all-UTF-8 setup, (such as "normal" Windows cmd.exe, they normally have ANSI encodings for average users) so testing and evaluating might become more difficult.)

Steps to reproduce:
　　Atom: 1.57.0 (Windows x64)
       Script: 3.31.3
       Grammar: java.js
       Java: AdoptOpenJDK 11.0.9.1 (HotSpot)

2021-05-12 04:13 UTC, aminya approved these changes
Thank you.

2021-05-12 04:15 UTC, aminya requested changes
I tried this and I get this error:
```
javac: invalid flag: ?J-Dfile.encoding=UTF-8
Usage: javac <options> <source files>
use -help for a list of possible options
[Finished in 0.694s]
```

2021-05-12 04:31 UTC, aminya approved these changes
Now it is fixed! :tada

2021-05-12 04:45 UTC, mhatano commented
Sorry for my typo. Thanks,

> I tried this and I get this error:
> 
> ```
> javac: invalid flag: ?J-Dfile.encoding=UTF-8
> Usage: javac <options> <source files>
> use -help for a list of possible options
> [Finished in 0.694s]
> ```

2021-05-12 04:47 UTC, merged

2022-02-01 01:13 UTC, lucas-berth commented
Hello: I am using Atom as well with Java and brand new install of JDK

Still getting this error even though it runs on VScode:
`error: invalid flag: Projects\My
Usage: javac <options> <source files>
use --help for a list of possible options`

I am not understanding how to fix this @aminya. It looks like you have the fix, but I am unsure how to fix this. Any help is appreciated.